name: STM32 builds
on:
  push:
  pull_request:
  # Run a build every month (at random time) to make sure firmware does not rot
  schedule:
    - cron: '27 2 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - RevA
          - RevC
          - nucleo
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      uses: docker://antoinealb/cvra-ci:latest
      with:
        args: bash -c "cd /github/workspace/ && make TARGET=${{ matrix.board }}"
